version: "1"
rules:
  - base: unstable 
    upstream: antirez:unstable
    mergeMethod: merge
  - base: 5.0 
    upstream: antirez:5.0
    mergeMethod: merge    
  - base: 4.0 
    upstream: antirez:4.0
    mergeMethod: merge    
  - base: 3.2 
    upstream: antirez:3.2
    mergeMethod: merge    
