version: 2
jobs:
  build:
    docker:
    - image: circleci/buildpack-deps
    steps:
    - checkout
    - run:
        name: Install dependency 
        command: sudo apt-get install -y tcl
    - run:
        name: Build
        command: make
    - run:
        name: Test
        command: make test
